<a href="https://colab.research.google.com/github/KILjungjoon/Term_Project/blob/main/Kpop_data_%ED%91%9C%EC%A4%80%ED%99%94%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# 파일 읽기
import pandas as pd
df=pd.read_excel("/content/drive/MyDrive/A Comparative Study on K-pop and T-pop in the Covid-19 Era/kpopSong.xlsx")
df

,year,week,rank,song,singer,album
0,2015,1,1,위아래,EXID,위아래
1,2015,1,2,LUV,에이핑크 (Apink),Pink LUV
2,2015,1,3,사랑에 빠지고 싶다,정승환,K팝 스타 시즌4 `사랑에 빠지고 싶다`
3,2015,1,4,Problem (Feat. Iggy Azalea),Ariana Grande,Problem
4,2015,1,5,Angel,"윤미래, 타이거JK, 비지",Angel
...,...,...,...,...,...,...
40095,2022,44,96,바라만 본다,MSG워너비(M.O.M),MSG워너비 1집
40096,2022,44,97,Permission to Dance,방탄소년단,Butter / Permission to Dance
40097,2022,44,98,인생은 뷰티풀,김호중,인생은 뷰티풀: 비타돌체
40098,2022,44,99,그때로 돌아가,로이킴,그때로 돌아가
40099,2022,44,100,Yet To Come,방탄소년단,Proof

In [3]:
# 컬럼 'album' 제거
df1=df.drop(labels='album',axis=1)

# 코로나 기간 중 매주 50위 곡 추출
kcovid=df1[(df1['year'] > 2019)&(df1['rank'] < 51)]   # 2020년 이후 50위까지 필터링
kcovid

,year,week,rank,song,singer
25500,2020,1,1,METEOR,창모 (CHANGMO)
25501,2020,1,2,Psycho,레드벨벳(Red Velvet)
25502,2020,1,3,"아마두 (Feat. 우원재, 김효은, 넉살, Huckleberry P)","염따 (YumDDa), 딥플로우, 팔로알토 (Paloalto), The Quiett..."
25503,2020,1,4,Blueming,아이유 (IU)
25504,2020,1,5,늦은 밤 너의 집 앞 골목길에서,노을
...,...,...,...,...,...
40045,2022,44,46,새벽에 걸려온 너의 전화는,한동근
40046,2022,44,47,스티커 사진,21학번
40047,2022,44,48,사랑한다고 말해줘,탑현
40048,2022,44,49,DICE,NMIXX
40049,2022,44,50,밤하늘의 별을(2020),경서

In [4]:
kcovid.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 7300 entries, 25500 to 40049
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   year    7300 non-null   int64
 1   week    7300 non-null   int64
 2   rank    7300 non-null   int64
 3   song    7300 non-null   object
 4   singer  7300 non-null   object
dtypes: int64(3), object(2)
memory usage: 342.2+ KB

In [5]:
# k_cvd_unq.xlsx를 불러온다.
import pandas as pd
df2=pd.read_excel("/content/drive/MyDrive/A Comparative Study on K-pop and T-pop in the Covid-19 Era/final-term/k_cvd_unq.xlsx")
df2

,song,singer,freq,lyrics,lyrics_tag,lyrics_notag,sadness,joy,anger,surprise,fear,disgust,interest,boredom,pain,others,neutral,positive,negative,tokens_num
0,00:00 (Zero O`Clock),방탄소년단,14,그런 날 있잖아 이유 없이 슬픈 날 몸은 무겁고 나 빼곤 모두 다 바쁘고 치열해 보...,그런/MM 날/NNG 있다/VA 잖아/EF 이유/NNG 없이/MAG 슬프다/VA ᆫ...,그런 날 있다 잖아 이유 없이 슬프다 ᆫ 날 몸 은 무겁다 고 나 빼다 곤 모두 다...,1,2,1,0,0,0,0,0,0,0,0,2,2,450
1,"08베이식 (Feat. 염따, punchnello)",베이식(Basick),2,지금 내 기분은 마치 08년도 베이식 데리고 와봐 네가 랩 잘한다는 새* 나는 조광...,지금/MAG 나/NP 의/JKG 기분/NNG 은/JX 마치/MAG 08/SN 년도/...,지금 나 의 기분 은 마치 08 년도 베이식 데리다 고 오다 아 보다 아 너 가 랩...,1,0,1,0,0,1,0,1,0,0,0,0,4,930
2,0X1=LOVESONG (I Know I Love You) (Feat. Seori),투모로우바이투게더,1,I know I love you 이 제로의 세계 속 I know you’re my ...,I/SL know/SL I/SL love/SL you/SL 이/NNG 제로/NNG ...,I know I love you 이 제로 의 세계 속 I know you ’ re ...,0,3,0,0,0,0,0,0,0,0,0,3,0,532
3,10억뷰 (Feat. MOON),세훈&찬열,1,넌 어느 별에서 왔길래 날 흔들어 놔 자꾸 소름 돋게 하고 내 맘을 헝클어 놓...,너/NP ᆫ/JX 어느/MM 별/NNG 에서/JKB 오다/VV 았/EP 길래/EC ...,너 ᆫ 어느 별 에서 오다 았 길래 나 ᆯ 흔들다 어 놓다 아 자꾸 소름 돋다 게 ...,0,0,0,0,1,0,0,0,0,0,0,0,1,288
4,12:45 (Stripped),Etham,7,It's 12 45 on a Tuesday I don't really care wh...,It/SL '/SSO s/SL 12/SN 45/SN on/SL a/SL Tuesda...,It ' s 12 45 on a Tuesday I don ' t really car...,0,0,0,0,0,0,0,0,0,0,0,0,0,362
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
620,회상,정경호,1,길을 걸었지\n누군가 옆에 있다고\n느꼈을 때\n나는 알아 버렸네\n이미 그대 떠난...,길/NNG 을/JKO 걷다/VV-I 었/EP 지/EC 누구/NP 이다/VCP ᆫ가/...,길 을 걷다 었 지 누구 이다 ᆫ가 옆 에 있다 다고 느끼다 었 을 때 나 는 알다...,1,0,3,1,0,0,0,0,2,0,0,0,7,225
621,"회전목마 (Feat. Zion.T, 원슈타인) (Prod. Slom)",sokodomo,33,내가 슬플 때마다\n이 노래가 찾아와\n세상이 둥근 것처럼 우린 동글동글\n\n인생...,나/NP 가/JKS 슬프다/VA ᆯ/ETM 때/NNG 마다/JX 이/MM 노래/NN...,나 가 슬프다 ᆯ 때 마다 이 노래 가 찾아오다 아 세상 이 둥글다 ᆫ 것 처럼 우...,3,3,0,0,1,0,0,1,1,0,0,3,6,489
622,흔들리는 꽃들 속에서 네 샴푸향이 느껴진거야,장범준,77,흔들리는 꽃들 속에서\n네 샴푸향이 느껴진거야\n스쳐지나간건가 뒤돌아보지만\n그냥 ...,흔들리다/VV 는/ETM 꽃들/NNG 속/NNG 에서/JKB 네/MM 샴푸/NNG ...,흔들리다 는 꽃들 속 에서 네 샴푸 향 이 느끼다 어 지다 ᆫ 거 이다 야 스치다 ...,6,0,0,0,0,0,0,0,0,0,0,0,6,309
623,흰눈,먼데이 키즈 (Monday Kiz),11,한 사람을 너무 사랑했던 거죠\n얼마나 나를\n아프게 할지도 모르고\n기뻐했죠\n이...,한/MM 사람/NNG 을/JKO 너무/MAG 사랑하다/VV 였/EP 던/ETM 거/...,한 사람 을 너무 사랑하다 였 던 거 이다 죠 얼마나 나 를 아프다 게 하다 ᆯ지 ...,1,2,0,0,0,0,0,0,1,0,0,2,2,249
624,힘든 건 사랑이 아니다,임창정,29,내가 널 떠났어야 했는데 왜 떠나야 하는지도 아는데\n어떤 아무 말도 아무것도 줄 ...,나/NP 가/JKS 너/NP ᆯ/JKO 떠나다/VV 았/EP 어야/EC 하다/VX ...,나 가 너 ᆯ 떠나다 았 어야 하다 였 는데 왜 떠나다 야 하다 는 지 도 알다 는...,2,1,0,0,0,0,0,0,1,0,0,1,3,365

In [6]:
ko_data = pd.merge(left=kcovid, right=df2, how='left')
ko_data
# ko_data.to_excel("/content/drive/MyDrive/A Comparative Study on K-pop and T-pop in the Covid-19 Era/final-term/ko_data.xlsx", index=False)

,year,week,rank,song,singer,freq,lyrics,lyrics_tag,lyrics_notag,sadness,...,fear,disgust,interest,boredom,pain,others,neutral,positive,negative,tokens_num
0,2020,1,1,METEOR,창모 (CHANGMO),71,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,Yeah/SL ha/SL Yeah/SL ha/SL Yeah/SL ha/SL Yeah...,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,1,...,0,0,1,0,0,0,0,1,2,453
1,2020,1,2,Psycho,레드벨벳(Red Velvet),38,Psycho 널 어쩌면 좋을까 이런 맘은 또 첨이라 Up &amp; Down이 좀...,Psycho/SL 너/NP ᆯ/JKO 어쩌다/VV 면/EC 좋다/VA 을까/EF 이...,Psycho 너 ᆯ 어쩌다 면 좋다 을까 이런 맘 은 또 첨 이다 라 Up & am...,3,...,1,0,1,0,0,0,0,4,6,522
2,2020,1,3,"아마두 (Feat. 우원재, 김효은, 넉살, Huckleberry P)","염따 (YumDDa), 딥플로우, 팔로알토 (Paloalto), The Quiett...",13,어 그래 얘들아 사는게 개같지 내 얼굴도 개같지 뭐얌 근데도 부자가 됐다 세상은 공...,어/IC 그렇다/VA 어/EF 얘/NP 들/XSN 아/JKV 살다/VV 는/ETM ...,어 그렇다 어 얘 들 아 살다 는 것 이 개 같다 지 나 의 얼굴 도 개 같다 지 ...,4,...,0,0,0,0,0,0,0,14,4,1141
3,2020,1,4,Blueming,아이유 (IU),86,‘뭐해?‘라는 두 글자에 ‘네가 보고 싶어’ 나의 속마음을 담아 우 이모티콘 하나하...,‘/SSO 뭐/NP 하다/VV 여/EF ?/SF ‘/SSO 이다/VCP 라는/ETM...,‘ 뭐 하다 여 ? ‘ 이다 라는 두 글자 에 ‘ 너 가 보다 고 싶다 어 ’ 나 ...,0,...,0,0,2,0,0,0,0,4,0,318
4,2020,1,5,늦은 밤 너의 집 앞 골목길에서,노을,66,오래되었어 그때 너의 웃음 너의 목소리 잊혀진거 같아 시간의 위로 그 말의 의미를 ...,오래/MAG 되/XSA 었/EP 어/EF 그때/NNG 너/NP 의/JKG 웃음/NN...,오래 되 었 어 그때 너 의 웃음 너 의 목소리 잊히다 어 지다 ᆫ 거 같다 아 시...,4,...,0,0,0,0,1,0,0,0,5,254
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7295,2022,44,46,새벽에 걸려온 너의 전화는,한동근,10,사랑한다 말하고 보고 싶다 말하고 많은 걸 약속하고 미래를 꿈꾸던 날들 내가 줬던 ...,사랑하다/VV ᆫ다/EF 말하다/VV 고/EC 보다/VV 고/EC 싶다/VX 다/E...,사랑하다 ᆫ다 말하다 고 보다 고 싶다 다 말하다 고 많다 은 거 ᆯ 약속하다 고 ...,9,...,1,0,0,0,1,0,0,1,12,302
7296,2022,44,47,스티커 사진,21학번,6,눈 감고 찍은 사진 장난스런 표정 하나둘 셋 하고서 손가락 하트 둘이서 연습했던 시...,눈/NNG 감다/VV 고/EC 찍다/VV 은/ETM 사진/NNG 장난/NNG 스럽/...,눈 감다 고 찍다 은 사진 장난 스럽 ᆫ 표정 하나 둘 셋 하다 고서 손가락 하트 ...,0,...,0,0,0,0,0,0,0,3,0,210
7297,2022,44,48,사랑한다고 말해줘,탑현,10,사실 난 너를 사랑한다고 말할 땐 너에게 그 말이 듣고 싶어서라고 오늘이 가기 전에...,사실/MAG 나/NP ᆫ/JX 너/NP 를/JKO 사랑하다/VV ᆫ다고/EC 말하다...,사실 나 ᆫ 너 를 사랑하다 ᆫ다고 말하다 ᆯ 때 ᆫ 너 에게 그 말 이 듣다 고 ...,4,...,0,0,0,0,0,0,0,1,4,315
7298,2022,44,49,DICE,NMIXX,1,번쩍 뜬 눈을 깜빡 머린 핑핑핑 돌아 상상도 못한 drama 첫 scene을 찍어볼...,번쩍/MAG 뜨다/VV ᆫ/ETM 눈/NNG 을/JKO 깜빡/MAG 머리/NNG ᆫ...,번쩍 뜨다 ᆫ 눈 을 깜빡 머리 ᆫ 핑핑 핑 돌다 아 상상 도 못 하 ᆫ drama...,0,...,1,0,0,0,0,0,0,2,1,433
7299,2022,44,50,밤하늘의 별을(2020),경서,65,밤하늘의 별을 따서 너에게 줄래 너는 내가 사랑하니까 더 소중하니까 오직 너 ...,밤/NNG 하늘/NNG 의/JKG 별/NNG 을/JKO 따다/VV 아서/EC 너/N...,밤 하늘 의 별 을 따다 아서 너 에게 주다 ᆯ래 너 는 나 가 사랑하다 니까 더 ...,2,...,0,0,0,1,0,0,0,4,3,370

In [7]:
ko_data.describe()

,year,week,rank,freq,sadness,joy,anger,surprise,fear,disgust,interest,boredom,pain,others,neutral,positive,negative,tokens_num
count,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.0,7300.0,7300.000000,7300.000000,7300.000000
mean,2020.952055,24.945205,25.500000,33.379452,1.691781,2.520411,0.238767,0.100959,0.328219,0.019041,0.126027,0.149589,0.400548,0.0,0.0,2.646438,2.928904,390.783014
std,0.805279,14.232803,14.431858,25.340647,2.354769,3.067134,0.992838,0.407592,0.845480,0.156318,0.513958,0.515103,0.876760,0.0,0.0,3.125376,3.115138,158.056266
min,2020.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,99.000000
25%,2020.000000,13.000000,13.000000,14.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,285.000000
50%,2021.000000,25.000000,25.500000,27.000000,1.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,2.000000,2.000000,353.000000
75%,2022.000000,37.000000,38.000000,51.000000,3.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,4.000000,4.250000,466.000000
max,2022.000000,51.000000,50.000000,108.000000,20.000000,17.000000,33.000000,3.000000,8.000000,3.000000,7.000000,4.000000,11.000000,0.0,0.0,17.000000,34.000000,1330.000000

* 각 감성 값을 표준화한 데이터프레임 만들기
* 표준화값=각 감성값/tokens_num

In [8]:
# 먼저 데이터프레임 틀 하나를 만든다.
kdata_stnd=ko_data.iloc[:, :9]
kdata_stnd

,year,week,rank,song,singer,freq,lyrics,lyrics_tag,lyrics_notag
0,2020,1,1,METEOR,창모 (CHANGMO),71,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,Yeah/SL ha/SL Yeah/SL ha/SL Yeah/SL ha/SL Yeah...,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...
1,2020,1,2,Psycho,레드벨벳(Red Velvet),38,Psycho 널 어쩌면 좋을까 이런 맘은 또 첨이라 Up &amp; Down이 좀...,Psycho/SL 너/NP ᆯ/JKO 어쩌다/VV 면/EC 좋다/VA 을까/EF 이...,Psycho 너 ᆯ 어쩌다 면 좋다 을까 이런 맘 은 또 첨 이다 라 Up & am...
2,2020,1,3,"아마두 (Feat. 우원재, 김효은, 넉살, Huckleberry P)","염따 (YumDDa), 딥플로우, 팔로알토 (Paloalto), The Quiett...",13,어 그래 얘들아 사는게 개같지 내 얼굴도 개같지 뭐얌 근데도 부자가 됐다 세상은 공...,어/IC 그렇다/VA 어/EF 얘/NP 들/XSN 아/JKV 살다/VV 는/ETM ...,어 그렇다 어 얘 들 아 살다 는 것 이 개 같다 지 나 의 얼굴 도 개 같다 지 ...
3,2020,1,4,Blueming,아이유 (IU),86,‘뭐해?‘라는 두 글자에 ‘네가 보고 싶어’ 나의 속마음을 담아 우 이모티콘 하나하...,‘/SSO 뭐/NP 하다/VV 여/EF ?/SF ‘/SSO 이다/VCP 라는/ETM...,‘ 뭐 하다 여 ? ‘ 이다 라는 두 글자 에 ‘ 너 가 보다 고 싶다 어 ’ 나 ...
4,2020,1,5,늦은 밤 너의 집 앞 골목길에서,노을,66,오래되었어 그때 너의 웃음 너의 목소리 잊혀진거 같아 시간의 위로 그 말의 의미를 ...,오래/MAG 되/XSA 었/EP 어/EF 그때/NNG 너/NP 의/JKG 웃음/NN...,오래 되 었 어 그때 너 의 웃음 너 의 목소리 잊히다 어 지다 ᆫ 거 같다 아 시...
...,...,...,...,...,...,...,...,...,...
7295,2022,44,46,새벽에 걸려온 너의 전화는,한동근,10,사랑한다 말하고 보고 싶다 말하고 많은 걸 약속하고 미래를 꿈꾸던 날들 내가 줬던 ...,사랑하다/VV ᆫ다/EF 말하다/VV 고/EC 보다/VV 고/EC 싶다/VX 다/E...,사랑하다 ᆫ다 말하다 고 보다 고 싶다 다 말하다 고 많다 은 거 ᆯ 약속하다 고 ...
7296,2022,44,47,스티커 사진,21학번,6,눈 감고 찍은 사진 장난스런 표정 하나둘 셋 하고서 손가락 하트 둘이서 연습했던 시...,눈/NNG 감다/VV 고/EC 찍다/VV 은/ETM 사진/NNG 장난/NNG 스럽/...,눈 감다 고 찍다 은 사진 장난 스럽 ᆫ 표정 하나 둘 셋 하다 고서 손가락 하트 ...
7297,2022,44,48,사랑한다고 말해줘,탑현,10,사실 난 너를 사랑한다고 말할 땐 너에게 그 말이 듣고 싶어서라고 오늘이 가기 전에...,사실/MAG 나/NP ᆫ/JX 너/NP 를/JKO 사랑하다/VV ᆫ다고/EC 말하다...,사실 나 ᆫ 너 를 사랑하다 ᆫ다고 말하다 ᆯ 때 ᆫ 너 에게 그 말 이 듣다 고 ...
7298,2022,44,49,DICE,NMIXX,1,번쩍 뜬 눈을 깜빡 머린 핑핑핑 돌아 상상도 못한 drama 첫 scene을 찍어볼...,번쩍/MAG 뜨다/VV ᆫ/ETM 눈/NNG 을/JKO 깜빡/MAG 머리/NNG ᆫ...,번쩍 뜨다 ᆫ 눈 을 깜빡 머리 ᆫ 핑핑 핑 돌다 아 상상 도 못 하 ᆫ drama...
7299,2022,44,50,밤하늘의 별을(2020),경서,65,밤하늘의 별을 따서 너에게 줄래 너는 내가 사랑하니까 더 소중하니까 오직 너 ...,밤/NNG 하늘/NNG 의/JKG 별/NNG 을/JKO 따다/VV 아서/EC 너/N...,밤 하늘 의 별 을 따다 아서 너 에게 주다 ᆯ래 너 는 나 가 사랑하다 니까 더 ...

In [9]:
ko_data.columns

Index(['year', 'week', 'rank', 'song', 'singer', 'freq', 'lyrics',
       'lyrics_tag', 'lyrics_notag', 'sadness', 'joy', 'anger', 'surprise',
       'fear', 'disgust', 'interest', 'boredom', 'pain', 'others', 'neutral',
       'positive', 'negative', 'tokens_num'],
      dtype='object')

In [10]:
# 다시 값이 0으로 채워진 빈 컬럼을 생성한다.
kdata_stnd[['sadness', 'joy', 'anger', 'surprise',
       'fear', 'disgust', 'interest', 'boredom', 'pain', 'others', 'neutral',
       'positive', 'negative']]=0
kdata_stnd

,year,week,rank,song,singer,freq,lyrics,lyrics_tag,lyrics_notag,sadness,...,surprise,fear,disgust,interest,boredom,pain,others,neutral,positive,negative
0,2020,1,1,METEOR,창모 (CHANGMO),71,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,Yeah/SL ha/SL Yeah/SL ha/SL Yeah/SL ha/SL Yeah...,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,0,...,0,0,0,0,0,0,0,0,0,0
1,2020,1,2,Psycho,레드벨벳(Red Velvet),38,Psycho 널 어쩌면 좋을까 이런 맘은 또 첨이라 Up &amp; Down이 좀...,Psycho/SL 너/NP ᆯ/JKO 어쩌다/VV 면/EC 좋다/VA 을까/EF 이...,Psycho 너 ᆯ 어쩌다 면 좋다 을까 이런 맘 은 또 첨 이다 라 Up & am...,0,...,0,0,0,0,0,0,0,0,0,0
2,2020,1,3,"아마두 (Feat. 우원재, 김효은, 넉살, Huckleberry P)","염따 (YumDDa), 딥플로우, 팔로알토 (Paloalto), The Quiett...",13,어 그래 얘들아 사는게 개같지 내 얼굴도 개같지 뭐얌 근데도 부자가 됐다 세상은 공...,어/IC 그렇다/VA 어/EF 얘/NP 들/XSN 아/JKV 살다/VV 는/ETM ...,어 그렇다 어 얘 들 아 살다 는 것 이 개 같다 지 나 의 얼굴 도 개 같다 지 ...,0,...,0,0,0,0,0,0,0,0,0,0
3,2020,1,4,Blueming,아이유 (IU),86,‘뭐해?‘라는 두 글자에 ‘네가 보고 싶어’ 나의 속마음을 담아 우 이모티콘 하나하...,‘/SSO 뭐/NP 하다/VV 여/EF ?/SF ‘/SSO 이다/VCP 라는/ETM...,‘ 뭐 하다 여 ? ‘ 이다 라는 두 글자 에 ‘ 너 가 보다 고 싶다 어 ’ 나 ...,0,...,0,0,0,0,0,0,0,0,0,0
4,2020,1,5,늦은 밤 너의 집 앞 골목길에서,노을,66,오래되었어 그때 너의 웃음 너의 목소리 잊혀진거 같아 시간의 위로 그 말의 의미를 ...,오래/MAG 되/XSA 었/EP 어/EF 그때/NNG 너/NP 의/JKG 웃음/NN...,오래 되 었 어 그때 너 의 웃음 너 의 목소리 잊히다 어 지다 ᆫ 거 같다 아 시...,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7295,2022,44,46,새벽에 걸려온 너의 전화는,한동근,10,사랑한다 말하고 보고 싶다 말하고 많은 걸 약속하고 미래를 꿈꾸던 날들 내가 줬던 ...,사랑하다/VV ᆫ다/EF 말하다/VV 고/EC 보다/VV 고/EC 싶다/VX 다/E...,사랑하다 ᆫ다 말하다 고 보다 고 싶다 다 말하다 고 많다 은 거 ᆯ 약속하다 고 ...,0,...,0,0,0,0,0,0,0,0,0,0
7296,2022,44,47,스티커 사진,21학번,6,눈 감고 찍은 사진 장난스런 표정 하나둘 셋 하고서 손가락 하트 둘이서 연습했던 시...,눈/NNG 감다/VV 고/EC 찍다/VV 은/ETM 사진/NNG 장난/NNG 스럽/...,눈 감다 고 찍다 은 사진 장난 스럽 ᆫ 표정 하나 둘 셋 하다 고서 손가락 하트 ...,0,...,0,0,0,0,0,0,0,0,0,0
7297,2022,44,48,사랑한다고 말해줘,탑현,10,사실 난 너를 사랑한다고 말할 땐 너에게 그 말이 듣고 싶어서라고 오늘이 가기 전에...,사실/MAG 나/NP ᆫ/JX 너/NP 를/JKO 사랑하다/VV ᆫ다고/EC 말하다...,사실 나 ᆫ 너 를 사랑하다 ᆫ다고 말하다 ᆯ 때 ᆫ 너 에게 그 말 이 듣다 고 ...,0,...,0,0,0,0,0,0,0,0,0,0
7298,2022,44,49,DICE,NMIXX,1,번쩍 뜬 눈을 깜빡 머린 핑핑핑 돌아 상상도 못한 drama 첫 scene을 찍어볼...,번쩍/MAG 뜨다/VV ᆫ/ETM 눈/NNG 을/JKO 깜빡/MAG 머리/NNG ᆫ...,번쩍 뜨다 ᆫ 눈 을 깜빡 머리 ᆫ 핑핑 핑 돌다 아 상상 도 못 하 ᆫ drama...,0,...,0,0,0,0,0,0,0,0,0,0
7299,2022,44,50,밤하늘의 별을(2020),경서,65,밤하늘의 별을 따서 너에게 줄래 너는 내가 사랑하니까 더 소중하니까 오직 너 ...,밤/NNG 하늘/NNG 의/JKG 별/NNG 을/JKO 따다/VV 아서/EC 너/N...,밤 하늘 의 별 을 따다 아서 너 에게 주다 ᆯ래 너 는 나 가 사랑하다 니까 더 ...,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
sentilist=[]
for n in range(0,7300) :
  df=pd.DataFrame([ko_data.iloc[n,9:-1]/ko_data.iloc[n, -1]])
  sentilist.append(df)

dfsenti=pd.concat(sentilist)
dfsenti

,sadness,joy,anger,surprise,fear,disgust,interest,boredom,pain,others,neutral,positive,negative
0,0.002208,0.000000,0.002208,0.000000,0.000000,0.0,0.002208,0.000000,0.000000,0.0,0.0,0.002208,0.004415
1,0.005747,0.005747,0.000000,0.003831,0.001916,0.0,0.001916,0.000000,0.000000,0.0,0.0,0.007663,0.011494
2,0.003506,0.012270,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.012270,0.003506
3,0.000000,0.006289,0.000000,0.000000,0.000000,0.0,0.006289,0.000000,0.000000,0.0,0.0,0.012579,0.000000
4,0.015748,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.003937,0.0,0.0,0.000000,0.019685
...,...,...,...,...,...,...,...,...,...,...,...,...,...
7295,0.029801,0.003311,0.003311,0.000000,0.003311,0.0,0.000000,0.000000,0.003311,0.0,0.0,0.003311,0.039735
7296,0.000000,0.014286,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.014286,0.000000
7297,0.012698,0.003175,0.000000,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.003175,0.012698
7298,0.000000,0.004619,0.000000,0.000000,0.002309,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.004619,0.002309
7299,0.005405,0.010811,0.000000,0.000000,0.000000,0.0,0.000000,0.002703,0.000000,0.0,0.0,0.010811,0.008108

In [29]:
kdata_stnd=pd.concat([kdata_stnd,dfsenti], axis=1)
kdata_stnd

,year,week,rank,song,singer,freq,lyrics,lyrics_tag,lyrics_notag,sadness,...,surprise,fear,disgust,interest,boredom,pain,others,neutral,positive,negative
0,2020,1,1,METEOR,창모 (CHANGMO),71,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,Yeah/SL ha/SL Yeah/SL ha/SL Yeah/SL ha/SL Yeah...,Yeah ha Yeah ha Yeah ha Yeah ha Yeah ha Yeah h...,0,...,0.000000,0.000000,0.0,0.002208,0.000000,0.000000,0.0,0.0,0.002208,0.004415
1,2020,1,2,Psycho,레드벨벳(Red Velvet),38,Psycho 널 어쩌면 좋을까 이런 맘은 또 첨이라 Up &amp; Down이 좀...,Psycho/SL 너/NP ᆯ/JKO 어쩌다/VV 면/EC 좋다/VA 을까/EF 이...,Psycho 너 ᆯ 어쩌다 면 좋다 을까 이런 맘 은 또 첨 이다 라 Up & am...,0,...,0.003831,0.001916,0.0,0.001916,0.000000,0.000000,0.0,0.0,0.007663,0.011494
2,2020,1,3,"아마두 (Feat. 우원재, 김효은, 넉살, Huckleberry P)","염따 (YumDDa), 딥플로우, 팔로알토 (Paloalto), The Quiett...",13,어 그래 얘들아 사는게 개같지 내 얼굴도 개같지 뭐얌 근데도 부자가 됐다 세상은 공...,어/IC 그렇다/VA 어/EF 얘/NP 들/XSN 아/JKV 살다/VV 는/ETM ...,어 그렇다 어 얘 들 아 살다 는 것 이 개 같다 지 나 의 얼굴 도 개 같다 지 ...,0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.012270,0.003506
3,2020,1,4,Blueming,아이유 (IU),86,‘뭐해?‘라는 두 글자에 ‘네가 보고 싶어’ 나의 속마음을 담아 우 이모티콘 하나하...,‘/SSO 뭐/NP 하다/VV 여/EF ?/SF ‘/SSO 이다/VCP 라는/ETM...,‘ 뭐 하다 여 ? ‘ 이다 라는 두 글자 에 ‘ 너 가 보다 고 싶다 어 ’ 나 ...,0,...,0.000000,0.000000,0.0,0.006289,0.000000,0.000000,0.0,0.0,0.012579,0.000000
4,2020,1,5,늦은 밤 너의 집 앞 골목길에서,노을,66,오래되었어 그때 너의 웃음 너의 목소리 잊혀진거 같아 시간의 위로 그 말의 의미를 ...,오래/MAG 되/XSA 었/EP 어/EF 그때/NNG 너/NP 의/JKG 웃음/NN...,오래 되 었 어 그때 너 의 웃음 너 의 목소리 잊히다 어 지다 ᆫ 거 같다 아 시...,0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.003937,0.0,0.0,0.000000,0.019685
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7295,2022,44,46,새벽에 걸려온 너의 전화는,한동근,10,사랑한다 말하고 보고 싶다 말하고 많은 걸 약속하고 미래를 꿈꾸던 날들 내가 줬던 ...,사랑하다/VV ᆫ다/EF 말하다/VV 고/EC 보다/VV 고/EC 싶다/VX 다/E...,사랑하다 ᆫ다 말하다 고 보다 고 싶다 다 말하다 고 많다 은 거 ᆯ 약속하다 고 ...,0,...,0.000000,0.003311,0.0,0.000000,0.000000,0.003311,0.0,0.0,0.003311,0.039735
7296,2022,44,47,스티커 사진,21학번,6,눈 감고 찍은 사진 장난스런 표정 하나둘 셋 하고서 손가락 하트 둘이서 연습했던 시...,눈/NNG 감다/VV 고/EC 찍다/VV 은/ETM 사진/NNG 장난/NNG 스럽/...,눈 감다 고 찍다 은 사진 장난 스럽 ᆫ 표정 하나 둘 셋 하다 고서 손가락 하트 ...,0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.014286,0.000000
7297,2022,44,48,사랑한다고 말해줘,탑현,10,사실 난 너를 사랑한다고 말할 땐 너에게 그 말이 듣고 싶어서라고 오늘이 가기 전에...,사실/MAG 나/NP ᆫ/JX 너/NP 를/JKO 사랑하다/VV ᆫ다고/EC 말하다...,사실 나 ᆫ 너 를 사랑하다 ᆫ다고 말하다 ᆯ 때 ᆫ 너 에게 그 말 이 듣다 고 ...,0,...,0.000000,0.000000,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.003175,0.012698
7298,2022,44,49,DICE,NMIXX,1,번쩍 뜬 눈을 깜빡 머린 핑핑핑 돌아 상상도 못한 drama 첫 scene을 찍어볼...,번쩍/MAG 뜨다/VV ᆫ/ETM 눈/NNG 을/JKO 깜빡/MAG 머리/NNG ᆫ...,번쩍 뜨다 ᆫ 눈 을 깜빡 머리 ᆫ 핑핑 핑 돌다 아 상상 도 못 하 ᆫ drama...,0,...,0.000000,0.002309,0.0,0.000000,0.000000,0.000000,0.0,0.0,0.004619,0.002309
7299,2022,44,50,밤하늘의 별을(2020),경서,65,밤하늘의 별을 따서 너에게 줄래 너는 내가 사랑하니까 더 소중하니까 오직 너 ...,밤/NNG 하늘/NNG 의/JKG 별/NNG 을/JKO 따다/VV 아서/EC 너/N...,밤 하늘 의 별 을 따다 아서 너 에게 주다 ᆯ래 너 는 나 가 사랑하다 니까 더 ...,0,...,0.000000,0.000000,0.0,0.000000,0.002703,0.000000,0.0,0.0,0.010811,0.008108

In [32]:
kdata_stnd.describe()

,year,week,rank,freq,sadness,joy,anger,surprise,fear,disgust,...,surprise,fear,disgust,interest,boredom,pain,others,neutral,positive,negative
count,7300.000000,7300.000000,7300.000000,7300.000000,7300.0,7300.0,7300.0,7300.0,7300.0,7300.0,...,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.000000,7300.0,7300.0,7300.000000,7300.000000
mean,2020.952055,24.945205,25.500000,33.379452,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000263,0.000828,0.000039,0.000296,0.000411,0.001155,0.0,0.0,0.007871,0.008452
std,0.805279,14.232803,14.431858,25.340647,0.0,0.0,0.0,0.0,0.0,0.0,...,0.001136,0.002127,0.000336,0.001179,0.001515,0.002441,0.0,0.0,0.009683,0.009443
min,2020.000000,1.000000,1.000000,1.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
25%,2020.000000,13.000000,13.000000,14.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000
50%,2021.000000,25.000000,25.500000,27.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.004429,0.006061
75%,2022.000000,37.000000,38.000000,51.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.011173,0.012270
max,2022.000000,51.000000,50.000000,108.000000,0.0,0.0,0.0,0.0,0.0,0.0,...,0.011538,0.021583,0.008242,0.013060,0.012821,0.029178,0.0,0.0,0.096591,0.063380